food_project/food/urls.py
from django.urls import path

from . import views

app_name = "food"

urlpatterns = [
    path("", views.FoodListView.as_view(), name="food_list"),
    path("<int:pk>", views.FoodDetailView.as_view(), name="food_detail"),
    path("new", views.FoodCreateView.as_view(), name="food_create"),
    path("update/<int:pk>", views.FoodUpdateView.as_view(),
         name="food_update"),
    path("delete/<int:pk>", views.FoodDeleteView.as_view(),
         name="food_delete"),
    path("bis/<int:pk>", views.FoodDetailbisView.as_view(), name="food_detail_bis",),
    path( "js/<int:pk>", views.FoodDetailJsView.as_view(), name="food_detail_js", ),
    
]

food_project/food_project/urls.py
from django.contrib import admin
from django.urls import path, include

import core.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", core.views.HomePageView.as_view(), name="homepage"),
    path("food/", include('food.urls', namespace='food')),
    path("orders/", include('orders.urls', namespace='orders'))

]

food_project/food/models.py
from django.db import models

# Create your models here.
class Food(models.Model):
    name = models.CharField(max_length=200, unique=True)
    price = models.SmallIntegerField()
    def __str__(self):
    		return self.name

food_project/food/forms.py
from django import forms

from .models import Food

class FoodForm(forms.ModelForm):
    class Meta:
        model = Food
        fields = ['name', 'price']

food_project/food/views.py
from django.shortcuts import render
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin


from .models import Food
from .forms import FoodForm

from django.forms.models import model_to_dict
from django.views import View
from django.shortcuts import get_object_or_404
from django.http import JsonResponse
from django.views.generic import TemplateView
# Create your views here.

class FoodListView(LoginRequiredMixin, ListView):
    model = Food

class FoodDetailView(LoginRequiredMixin, DetailView):
    model = Food

class FoodCreateView(LoginRequiredMixin, CreateView):
    model = Food
    fields = ['name','price']

    def form_valid(self, form):
        response = super().form_valid(form)
        messages.add_message(
            self.request, messages.SUCCESS,
            'Food "{food_name}" has been created'.format(
                food_name=self.object.name))
        return response

    def get_success_url(self):
    	return reverse_lazy("food:food_detail_bis", args=[self.object.id])

class FoodDeleteView(LoginRequiredMixin, DeleteView):
    model = Food
    success_url = reverse_lazy("food:food_list")


    def form_valid(self, form):
        response = super().form_valid(form)
        messages.add_message(
            self.request, messages.SUCCESS,
            'Food "{food_name}" has been deleted'.format(
                food_name=self.object.name))
        return response

class FoodUpdateView(LoginRequiredMixin, UpdateView):
    model = Food
    fields = ['name','price']

    def form_valid(self, form):
        response = super().form_valid(form)
        messages.add_message(
            self.request, messages.SUCCESS,
            'Food "{food_name}" has been updated'.format(
                food_name=self.object.name))
        return response

    def get_success_url(self):
    	return reverse_lazy("food:food_detail_bis", args=[self.object.id])

    
class FoodDetailbisView(TemplateView):
    template_name = "food/food_detailbis.html"
    def get(self, request, *args, **kwargs):
        food = get_object_or_404(Food, pk=self.kwargs["pk"])
        return super().get(request, *args, **kwargs)
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['food_id'] = self.kwargs["pk"]
        return context

class FoodDetailJsView(View):
    def get(self, request, *args, **kwargs):
        food = get_object_or_404(Food, pk=self.kwargs["pk"])
        food_js = model_to_dict(food)
        return JsonResponse({"food": food_js})

food_project/food/templates/food/food_confirm_delete.html
{% extends "base.html" %}

{% block content %}
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete the food "{{ object.name }}"?</p>
    {{ form.as_p }}
    <input type="submit" value="Confirm">
</form>
{% endblock content %}

food_project/food/templates/food/food_detail.html
{% extends "base.html" %} {% block content %} <a href="{% url 'food:food_list' %}">Food list</a><br /><br />
<a href="{% url 'food:food_update' object.id %}">Update Food</a><br />
<a href="{% url 'food:food_delete' object.id %}">Delete Food</a><br />
<h1>{{ object.name }}</h1>
<h1>{{ object.price }}</h1>
{% endblock content %}

food_project/food/templates/food/food_detailbis.html
{% extends "base.html" %} {% load django_vite %} {% block content %}
<div id="app">
	<app></app>
</div>
{% endblock content %} {% block js %} {{ block.super }}
<script>
	var ext_id = '{{ object.id | safe }}';
	var ext_food_detail_js_url = '{% url 'food:food_detail_js' food_id %}';
	var ext_food_list_url = '{% url 'food:food_list' %}';
    var ext_food_update_url = '{% url 'food:food_update' food_id %}';
	var ext_food_delete_url ='{% url 'food:food_delete' food_id %}';
</script>
{% vite_hmr_client %} {% vite_asset 'src/apps/food_detail/food_detail.js' %} {% endblock js %}

food_project/food/templates/food/food_form.html
{% extends "base.html" %} {% load django_vite %} {% block content %} {% csrf_token %} 
<div id="app">
	<app></app>
</div>
{% endblock content %} {% block js %} {{ block.super }}
<script>
	var ext_csrf_token = '{{ csrf_token }}';
	var ext_form = `{{ form.as_p | safe}}`;
	var ext_name = '{{ object.name | safe }}';
	var ext_price = '{{ object.price | safe }}';
</script>
{% vite_hmr_client %} {% vite_asset 'src/apps/food_edit/food_edit.js' %} {% endblock js %}

food_project/food/templates/food/food_list.html
{% extends "base.html" %}

{% block content %}
<br>
<a href="{% url 'food:food_create' %}"> <button>New Food item </button></a><br/><br/>
Food: <br>
{% for food in object_list %}
<a href="{% url 'food:food_detail_bis' food.id %}">{{ food.name }}</a><br/>
{% endfor %}
{% endblock content %}