food_project/food/urls.py
from django.urls import path

from . import views

app_name = "food"

urlpatterns = [
    path("", views.FoodListView.as_view(), name="food_list"),
    path("<int:pk>", views.FoodDetailView.as_view(), name="food_detail"),
    path("new", views.FoodCreateView.as_view(), name="food_create"),
    path("update/<int:pk>", views.FoodUpdateView.as_view(),
         name="food_update"),
    path("delete/<int:pk>", views.FoodDeleteView.as_view(),
         name="food_delete"),
    path("bis/<int:pk>", views.FoodDetailbisView.as_view(), name="food_detail_bis",),
    path( "js/<int:pk>", views.FoodDetailJsView.as_view(), name="food_detail_js", ),
    
]

food_project/food_project/urls.py
from django.contrib import admin
from django.urls import path, include

import core.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", core.views.HomePageView.as_view(), name="homepage"),
    path("food/", include('food.urls', namespace='food')),
    path("orders/", include('orders.urls', namespace='orders'))

]

food_project/orders/urls.py
from django.urls import path

from . import views

app_name = "order"

urlpatterns = [
    path("", views.OrderListView.as_view(), name="order_list"),
    path("<int:pk>", views.OrderDetailView.as_view(), name="order_detail"),
    path("new", views.OrderCreateView.as_view(), name="order_create"),
    path("update/<int:pk>", views.OrderUpdateView.as_view(),
         name="order_update"),
    path("delete/<int:pk>", views.OrderDeleteView.as_view(),
         name="order_delete"),
    path("bis/<int:pk>", views.OrderDetailbisView.as_view(), name="order_detail_bis",),
    path( "js/<int:pk>", views.OrderDetailJsView.as_view(), name="order_detail_js", ),
]

food_project/core/models.py
from django.db import models

# Create your models here.

food_project/core/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required


class HomePageView(TemplateView):
    template_name = "core/home.html"

food_project/core/templates/base.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
	{% block head %}
	{% endblock head %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <title>Food Project App</title>
</head>

<body class="d-flex flex-column min-vh-100">
    {% url 'logout' as url_logout %}
    {% url 'login' as url_login %}
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="row">
                    <div class="col-5 d-flex align-items-center pb-1">
                        Food Project App
                    </div>
                    <div class="col-7 d-flex align-items-center">
                        <div class="row" style="width: 110%">
                            <div class="col">
                                <div class="float-end">
                                        {% if user.is_authenticated %}
                                            <div class="row">
                                                <div class="col-auto d-flex align-items-center">
                                                    login: {{user.username}}
                                                </div>
                                                <div class="col-auto">
                                                    <form action="{{url_logout}}" method="post">
                                                        {% csrf_token %}
                                                        <button type="submit" class="btn btn-primary ms-3 pull-right" id="logbtn">Logout</button>
                                                    </form>
                                                </div>
                                            </div>
                                        {% else %}
                                            <div class="col">
                                                <a class="btn btn-primary" href="{{ url_login }}" role="button">Login</a>
                                            </div>
                                        {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <nav class="navbar navbar-expand-sm bg-light">
            <div class="container">
                
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'homepage' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'food:food_list' %}">Food</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'orders:order_list' %}">Orders</a>
                    </li>
                </ul>
            </div>
        </nav>
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
        {% block content %}
        {% endblock content %}
    </div>
</body>

{% block js %}
	{% endblock js %}
    

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></scrip>
    <scrip src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>


</html>