food_project/food/urls.py
from django.urls import path

from . import views

app_name = "food"

urlpatterns = [
    path("", views.FoodListView.as_view(), name="food_list"),
    path("<int:pk>", views.FoodDetailView.as_view(), name="food_detail"),
    path("new", views.FoodCreateView.as_view(), name="food_create"),
    path("update/<int:pk>", views.FoodUpdateView.as_view(),
         name="food_update"),
    path("delete/<int:pk>", views.FoodDeleteView.as_view(),
         name="food_delete"),
    path("bis/<int:pk>", views.FoodDetailbisView.as_view(), name="food_detail_bis",),
    path( "js/<int:pk>", views.FoodDetailJsView.as_view(), name="food_detail_js", ),
    
]

food_project/food_project/urls.py
from django.contrib import admin
from django.urls import path, include

import core.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", core.views.HomePageView.as_view(), name="homepage"),
    path("food/", include('food.urls', namespace='food')),
    path("orders/", include('orders.urls', namespace='orders'))

]

food_project/orders/urls.py
from django.urls import path

from . import views

app_name = "order"

urlpatterns = [
    path("", views.OrderListView.as_view(), name="order_list"),
    path("<int:pk>", views.OrderDetailView.as_view(), name="order_detail"),
    path("new", views.OrderCreateView.as_view(), name="order_create"),
    path("update/<int:pk>", views.OrderUpdateView.as_view(),
         name="order_update"),
    path("delete/<int:pk>", views.OrderDeleteView.as_view(),
         name="order_delete"),
    path("bis/<int:pk>", views.OrderDetailbisView.as_view(), name="order_detail_bis",),
    path( "js/<int:pk>", views.OrderDetailJsView.as_view(), name="order_detail_js", ),
]

food_project/orders/models.py
from django.db import models
from food.models import Food
# Create your models here.
class Order(models.Model):
    customer = models.CharField(max_length=200, unique=True)
    total_price = models.SmallIntegerField()
    food = models.ManyToManyField(Food)

    def __str__(self):
    		return self.customer

food_project/orders/forms.py
from django import forms

from .models import Order

class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['customer', 'total_price','food']

food_project/orders/views.py
from django.shortcuts import render
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin


from .models import Order
from food.models import Food
from .forms import OrderForm

from django.forms.models import model_to_dict
from django.views import View
from django.shortcuts import get_object_or_404
from django.http import JsonResponse
from django.views.generic import TemplateView
# Create your views here.

class OrderListView(LoginRequiredMixin, ListView):
    model = Order

class OrderDetailView(LoginRequiredMixin, DetailView):
    model = Order

class OrderCreateView(LoginRequiredMixin, CreateView):
    model = Order
    fields = ['customer','total_price', 'food']


    def form_valid(self, form):
        response = super().form_valid(form)
        messages.add_message(
            self.request, messages.SUCCESS,
            'Order for "{customer}" has been created'.format(
                customer=self.object.customer))
        return response

    def get_context_data(self, **kwargs):
       context = super().get_context_data(**kwargs)
       all_food = list(Food.objects.all().values())
       context["orders_list"] = dict(food=[])
       context["food_list"] = all_food
       print("context", context)
       return context
    
    def get_success_url(self):
    	return reverse_lazy("order:order_detail_bis", args=[self.object.id])

class OrderDeleteView(LoginRequiredMixin, DeleteView):
    model = Order
    success_url = reverse_lazy("order:order_list")


    def form_valid(self, form):
        response = super().form_valid(form)
        messages.add_message(
            self.request, messages.SUCCESS,
            'Order for "{customer}" has been deleted'.format(
                customer=self.object.customer))
        return response

class OrderUpdateView(LoginRequiredMixin, UpdateView):
    model = Order
    fields = ['customer','total_price', 'food']

    def form_valid(self, form):
        response = super().form_valid(form)
        messages.add_message(
            self.request, messages.SUCCESS,
            'Order for "{customer}" has been updated'.format(
                customer=self.object.customer))
        return response

    def get_context_data(self, **kwargs):
       context = super().get_context_data(**kwargs)
       orders_dico = model_to_dict(self.object)
       food = orders_dico["food"]
       food_list = []
       for someFood in food:
           food_list.append({"id": someFood.id, "name": someFood.name, "price": someFood.price})
       orders_dico["food"] = food_list
       all_food = list(Food.objects.all().values())
       context["orders_list"] = orders_dico
       context["food_list"] = all_food
       print("context", context)
       return context
   
    def get_success_url(self):
    	return reverse_lazy("order:order_detail_bis", args=[self.object.id])
 
class OrderDetailbisView(TemplateView):
    template_name = "orders/order_detailbis.html"
    
    def get(self, request, *args, **kwargs):
        order = get_object_or_404(Order, pk=self.kwargs["pk"])
        return super().get(request, *args, **kwargs)
    
    def get_context_data(self, **kwargs):
        order = get_object_or_404(Order, pk=self.kwargs["pk"])
        context = super().get_context_data(**kwargs)
        orders_dico = model_to_dict(order)
        food = orders_dico["food"]
        food_list = []
        for someFood in food:
            food_list.append({"id": someFood.id, "name": someFood.name, "price": someFood.price})
        orders_dico["food"] = food_list
        context["orders_list"] = orders_dico
        context['order_id'] = self.kwargs["pk"]
        return context

class OrderDetailJsView(View):
    def get(self, request, *args, **kwargs):
        order = get_object_or_404(Order, pk=self.kwargs["pk"])
        order_js = model_to_dict(order)
        return JsonResponse({"order": order_js})

food_project/orders/templates/orders/order_confirm_delete.html
{% extends "base.html" %}

{% block content %}
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete the order for "{{ object.customer }}"?</p>
    {{ form.as_p }}
    <input type="submit" value="Confirm">
</form>
{% endblock content %}

food_project/orders/templates/orders/order_detail.html
{% extends "base.html" %} {% block content %} <a href="{% url 'order:order_list' %}">Order list</a><br /><br />
<a href="{% url 'order:order_update' object.id %}">Update order</a><br />
<a href="{% url 'order:order_delete' object.id %}">Delete order</a><br />
<h1>{{ object.customer }}</h1>
<h1>{{ object.total_price }}</h1>
Food:<br />
{% for food in object.food.all %} {{food.name}}<br />
{% endfor %}
<br />
{% endblock content %}

food_project/orders/templates/orders/order_detailbis.html
{% extends "base.html" %} {% load django_vite %} {% block content %}
<div id="app">
	<app></app>
</div>
{% endblock content %} {% block js %} {{ block.super }}
<script>
	var ext_id = '{{ order_id | safe }}';
    var ext_order_dico = {{ orders_list | safe }};
	var ext_order_detail_js_url = '{% url 'order:order_detail_js' order_id %}';
	var ext_order_list_url = '{% url 'order:order_list' %}';
    var ext_order_update_url = '{% url 'order:order_update' order_id %}';
	var ext_order_delete_url ='{% url 'order:order_delete' order_id %}';
</script>
{% vite_hmr_client %} {% vite_asset 'src/apps/order_detail/order_detail.js' %} {% endblock js %}

food_project/orders/templates/orders/order_form.html
{% extends "base.html" %} 
{% load django_vite %} 
{% block content %} 
{% csrf_token %}

<div id="app">
	<app></app>
</div>
{% endblock content %} 
{% block js %} 
{{ block.super }}
<script>
	var ext_csrf_token = '{{ csrf_token }}';
	var ext_form = `{{ form.as_p | safe}}`;
	var ext_customer = '{{ object.customer | safe }}';
	var ext_total_price = '{{ object.total_price | safe }}';
	var ext_order_dico = {{ orders_list | safe}};
	var ext_food_list = {{ food_list | safe}};
</script>
{% vite_hmr_client %} 
{% vite_asset 'src/apps/order_edit/order_edit.js' %} 
{% endblock js %}

food_project/orders/templates/orders/order_list.html
{% extends "base.html" %} {% block content %} 
<br>
<a href="{% url 'order:order_create' %}"> <button>New order item</button></a><br /><br />
Orders: <br>
{% for order in object_list %}
<a href="{% url 'order:order_detail_bis' order.id %}">{{ order.customer }}</a><br />
{% endfor %} {% endblock content %}